#!/bin/sh /etc/rc.common
#
# IMPORTANT: This initscript does not work on non OpenWRT systems!
#            Use the systemd unit if you are trying to run this on a Debian system.

USE_PROCD=1

CMD=/usr/bin/iw2mqtt
PIDFILE=/var/run/iw2mqtt.pid

start_service() {
    # FIXME: jail this because it shouldn't need access to anything else and that sounds like good best-practice
    #        ref: https://openwrt.org/docs/guide-developer/procd-init-scripts#service_jails
    procd_open_instance
    procd_set_param command $CMD
    procd_set_param pidfile $PIDFILE
    # FIXME: Does 'iw event' work when run as nobody?
    # procd_set_param user nobody
    procd_close_instance
}

stop_service() {
    # procd only sends a sigterm to the parent process, it does not kill the whole process group
    # This is a shitty workaround for that
    test -f "$PIDFILE" || exit
    main_pid=$(cat $PIDFILE)
    # FIXME, might there be TOCTOU issues here that result in the wrong processes being killed?
    # FIXME: I did get the impression that `kill $(pgrep -P $main_pid)` might be good enough, just do that?
    child_pids=$(pgrep -P $main_pid | while read pid ; do echo $pid ; pgrep -P "$pid" ; done)
    # FIXME: Doesn't do any sort of "wait 10 then SIGKILL", but that'd be really hard for this
    kill $child_pids
}

reload_service() {
        echo "Reload not supported, forcing restart" >&2
        stop
        start
}
